### ISSUE TITLE
Installs org-mode when org-plus-contrib is installed

### ISSUE THREAD

**Issue by ljos** [magit/org-magit#5]
Because of the `;; Package-Requires: ((magit "1.2.0") (org "6.01"))` org is installed even though `org-plus-contrib` is installed.

**Comment by tarsius** [comment]
Could you please ask the Org guys what they think we should do about this. Because `package.el` does not support "alternatives" (as in `(|| (org "0") (org-plus-contrib "0"))` I think the only real solution would be to replace `org-plus-contrib` with `org-contrib` (which would depend on `org`).

All packages which depend on Org have this problem, so I am closing this. Not depending on `org` doesn't really seem like a good approach either. But please report here what the Org maintainers have to say on the matter.
