### ISSUE TITLE
Issues with the next branch

### ISSUE THREAD

**Issue by Malabarba** [magit/org-magit#6]
I'm running the magit next branch, and some of the features don't work.
The magit next branch isn't released yet, but I figured the developer might want to be aware of this issue ahead of time.

- `org-store-link` in the commit buffer doesn't seem to do anything.
- Creating a status link works, but opening does not work. The status buffer is created, but is not displayed. I'm no expert on the inner workings of this package, but the reason for this *seems* to be that the `(apply func args)` snippet inside `org-magit-open` doesn't do anything. Value of `func` is just `current-buffer` (which is a pure function).
- Crealing a log link works, but opening also doesn't. This one throws a `Wrong number of arguments` error.

Cheers, and thanks for the package

**Comment by tarsius** [comment]
Please use the successor `orgit` - it is more powerful and works with the upcoming release.

I have kept this repository for now because it is still useful for people who don't want to migrate their links to the new format. But I do not intend to make this compatible with the upcoming release.

If there are interested parties (like @sigma the original author) who would like to maintain this, then I would welcome that. Otherwise I will likely remove this once `2.1.0` is released.

**Comment by Malabarba** [comment]
Ok thanks. I'll try it out.

**Comment by mjhoy** [comment]
@tarsius i'd be interested in maintaining if no one else is, i would rather not switch to orgit.
